let a,b,c,d,e,f;
let saida = document.getElementById("saida");
a=50;
b=120;
c=200;
d=(a<=b) ? "Verdadeiro" : "Falso";
e=(a>=c) ? "Verdadeiro" : "Falso";
f=(a%2==0)?"Par" : "impar";
saida.innerHTML=`d = ${d}<br>`;
saida.innerHTML+=`e = ${e}<br>` ;
saida.innerHTML+=`a = ${a} - é ${f}`;